# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
a1 = Actor.create(name: "Robert downey Jr", image: "http://media.sdreader.com/img/photos/2014/01/16/robert-downey-jr-photo-1024x768.jpg", biography: "Robert Downey Jr. has evolved into one of the most respected actors in Hollywood. With an amazing list of credits to his name, he has managed to stay new and fresh even after over four decades in the business.")
a2 = Actor.create(name: "Scarlett Johansson", image: "http://si.wsj.net/public/resources/images/BN-BY925_mag041_OZ_20140318165119.jpg", biography: "Scarlett Johansson born November 22, 1984) is an American actress, model, and singer. She made her film debut in North (1994). In 1996, she was nominated for the Independent Spirit Award for Best Female Lead for her performance in Manny & Lo, garnering further acclaim and prominence with roles in The Horse Whisperer ")
a3 = Actor.create(name: "Chris Evans", image: "https://upload.wikimedia.org/wikipedia/commons/2/25/Chris_Evans_SDCC_2014.jpg", biography: "Chris Evans is an American actor and film director. Evans is best known for his superhero roles as the Marvel Comics characters Steve Rogers / Captain America in the Marvel Cinematic Universe and Johnny Storm / Human Torch in Fantastic Four (2005) and Fantastic Four: Rise of the Silver Surfer (2007).")
a4 = Actor.create(name: "Mark Ruffalo", image: "http://hamptonsfilmfest.org/site/wp-content/uploads/2014/09/MarkRuffalo.jpg", biography: "Mark Alan Ruffalo is an American actor, director, producer and screenwriter. He has portrayed the Marvel Comics character Dr. Bruce Banner / the Hulk in The Avengers. Other notable films in which he has starred or co-starred are Shutter Island 2010, Now You See Me 2013. For his roles in The Kids Are All Right (2010) and Foxcatcher (2014), he received Academy Award nominations for Best Supporting Actor." )
a5 = Actor.create(name: "Chris Hemsworth", image: "http://photos.laineygossip.com/articles/chris-hemsworth-sarah-09jan15-07.jpg", biography: "Chris Hemsworth is an Australian actor. He is best known for his roles as Thor in the Marvel Cinematic Universe films Thor, The Avengers. He has also appeared in the science fiction action film Star Trek 2009, biographical sports drama film Rush" )
a6 = Actor.create(name: "Jeremy Renner", image: "http://hatchexperience.org/wp-content/uploads/2015/04/jeremy-renner-wallpaper1.jpg", biography: "jeremy Lee Renner  is an American actor, singer, and film producer.Renner is best known for his roles in The Hurt Locker, for playing Hawkeye in Marvel's The Avengers . He also appeared in Mission: Impossible – Ghost Protocol  ")
a7 = Actor.create(name: "Tom Hiddleston", image: "http://now-here-this.timeout.com/wp-content/uploads/2013/05/Tom-Hiddleston.jpg", biography: "Thomas William  Hiddleston is an English actor. He is best known for his role as Loki in the Marvel Cinematic Universe. He also appeared in War Horse. In theatre, he has been in the productions of Cymbeline  ")
a8 = Actor.create(name: "Sameul L Jackson", image: "http://www.wickedhorror.com/wp-content/uploads/2015/05/Samuel-L-Jackson.jpg", biography: "Samuel Leroy Jackson is an American actor and film producer. He achieved prominence and critical acclaim in the early 1990s with films such as Jungle Fever, Amos & Andrew ,Jurassic Park and Pulp Fiction. He is a highly prolific actor, appearing in over 100 films, including Die Hard with a Vengeance (1995), Unbreakable (2000), The 51st State (2001), and the Star Wars prequel trilogy (1999–2005), as well as the Marvel Cinematic Universe.")
a9 = Actor.create(name: "Benedict Cumberbatch", image: "http://i.huffpost.com/gen/1633328/original.jpgg", biography: "Benedict Timothy Carlton Cumberbatch is an English actor and film producer who has performed in film, television, theatre and radio. The son of actors Timothy Carlton and Wanda Ventham, he graduated from the University of Manchester and continued his training at the London Academy of Music and Dramatic Art, obtaining a Master of Arts in Classical Acting.")
a10 = Actor.create(name: "Gwyneth Paltrow", image: "http://www.adweek.com/prnewser/wp-content/uploads/sites/8/2015/04/gwyneth-paltrow.jpg", biography: "GGwyneth Kate Paltrow is an American actress, singer, and food writer. Paltrow gained early notice for her work in films such as the psychological thriller Seven (1995), the period drama Emma (1996), Following starring roles comedy-drama Sliding Doors (1998) and  A Perfect Murder, Paltrow garnered worldwide recognition through her performance in Shakespeare in Love (1998), for which she won an Academy Award for Best Actress, a Golden Globe Award and two Screen Actors Guild Awards, for Outstanding Lead Actress and as a member of the Outstanding Cast.")
a11 = Actor.create(name: "Chris Pine", image: "http://www.followingthenerd.com/site/wp-content/uploads/chris-pine.jpg", biography: "Christopher Whitelaw Pine is an American actor in film and television. He is best known for his role as James T. Kirk in the 2009 film Star Trek, and has also appeared in films including: The Princess Diaries 2: Royal Engagement (2004), Unstoppable (2010), This Means War (2012), Rise of the Guardians (2012), Horrible Bosses 2 (2014), as Jack Ryan in Jack Ryan: Shadow Recruit (2014),..")
a12 = Actor.create(name: "Zachary Quinto",  image: "https://pmcdeadline2.files.wordpress.com/2014/01/zachary-quinto-photo.jpg", biography: "Zachary John Quinto is an American actor and film producer. He is best known for his roles as Sylar in the science fiction drama series Heroes (2006–2010), and Spock in Star Trek . He also appeared in smaller roles on television series such as So NoTORIous and 24, and was nominated for a Primetime Emmy Award for his performance in American Horror Story: Asylum.")
a13 = Actor.create(name: "Zoe Saldana",  image: "http://vignette1.wikia.nocookie.net/marvelmovies/images/8/87/Zoe_Saldana.jpg/revision/latest?cb=20130425125632", biography: "oe Yadira Saldaña Nazario, is an American actress, producer and dancer. Following her performances with the FACES theater group, Saldana made her screen debut in an episode of Law & Order. Saldana's also starred as Nyota Uhura in Star Trek and played the lead role of Neytiri in James Cameron's Avatar ")
a14 = Actor.create(name: "Brad Pitt",  image: "http://img2.timeinc.net/people/i/2007/specials/sma07/mag/brad_pitt.jpg", biography: "Jilliam Bradley Pitt is an American actor and producer. He has received a Golden Globe Award, a Screen Actors Guild Award, and three Academy Award nominations in acting categories, and received two further Academy Award nominations, winning one, for productions of his film production company Plan B Entertainment.")
a15 = Actor.create(name: "Emma Stone",image: "http://media1.popsugar-assets.com/files/2014/05/02/248/n/1922398/95858757dd9d1bef_thumb_temp_image347054901399053000/i/Im-Huge-Fan-Emma-Stone-Part-1-Video.jpg", biography: "Emily Jean Stone is an American actress. She made her feature film debut in the comedy Superbad .In 2010, Stone made her leading debut in the comedy Easy A, for which she received a nomination for the Golden Globe Award for Best Actress. Stone's other films include the romantic comedy-drama Crazy, Stupid, Love (2011), The Amazing Spider-Man film series as Gwen Stacy ")
a16 = Actor.create(name: "Angelina Jolie", image: "http://photos.laineygossip.com/articles/angelina-jolie-parenting-21may14-07.jpg", biography: "Angelina Jolie Pitt is an American actress, filmmaker, and humanitarian. She has received an Academy Award, two Screen Actors Guild Awards, and three Golden Globe Awards, and has been cited as Hollywood's highest-paid actress.")
a16 = Actor.create(name: "Sam worthington", image: "https://upload.wikimedia.org/wikipedia/commons/d/de/Sam_Worthington_4,_2013.jpg", biography: "Samuel Henry John  Worthington is an Australian actor, best known for the portrayals of Jake Sully in Avatar, Marcus Wright in Terminator Salvation, Perseus in Clash of the Titans and its sequel, Wrath of the Titans, and Alex Mason in the video game Call of Duty: Black Ops and its sequel Call of Duty: Black Ops II.")

m1 = Movie.create(movie_title: "Avengers", image: "http://tonygentilcore.com/wp-content/uploads/2015/05/Avengers-Age-of-Ultron.jpg", release_year: "2015", synopsis: "When Tony Stark and Bruce Banner try to jump-start a dormant peacekeeping program called Ultron, things go horribly wrong and it's up to Earth's Mightiest Heroes to stop the villainous Ultron from enacting his terrible plans.")
m2 = Movie.create(movie_title: "Star Trek: Into Darkness", image: "http://www.treknews.net/wp-content/uploads/2013/03/empire-magazine-star-trek-into-darkness.jpg", release_year: "2013",synopsis: "After the crew of the Enterprise find an unstoppable force of terror from within their own organization, Captain Kirk leads a manhunt to a war-zone world to capture a one-man weapon of mass destruction.")
m3 = Movie.create(movie_title: "Star wars: attack of the Clone", image: "http://mtv.mtvnimages.com/shared/media/images/acovers/standard/drb200/b204/b20481tzkl4.jpg", release_year: "2002", synopsis: "Ten years after initially meeting, Anakin Skywalker shares a forbidden romance with Padmé, while Obi-Wan investigates an assassination attempt on the Senator and discovers a secret clone army crafted for the Jedi.")
m4 = Movie.create(movie_title: "Rush", image: "http://sim02.in.com/292f724d88189ac048384c9782ec1bde_p_m.jpg", release_year: "2013", synopsis: "The merciless 1970s rivalry between Formula One rivals James Hunt and Niki Lauda")
m5 = Movie.create(movie_title: "Guardians of the galaxy", image: "http://wp.production.patheos.com/blogs/thegodarticle/files/2014/08/guardian-of-the-galaxy-poster1.jpg", release_year: "2014", synopsis: "A group of intergalactic criminals are forced to work together to stop a fanatical warrior from taking control of the universe.")
m6 = Movie.create(movie_title: "Mr and Mrs Smith", image: "http://i.jeded.com/i/mr-and-mrs-smith-2005.11281.jpg", release_year: "2007",synopsis: "Newly relocated to the suburbs, married assassins John and Jane Smith have re-established their respective businesses, though the marital issues that plagued them in the past have returned.")
m7 = Movie.create(movie_title: "Iron Man 3", image: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d5/Iron_Man_3_theatrical_poster.jpg/220px-Iron_Man_3_theatrical_poster.jpg", release_year: "2013", synopsis: "When Tony Stark's world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution.")
m8 = Movie.create(movie_title: "The Amazing Spiderman", image: "https://upload.wikimedia.org/wikipedia/en/0/02/The_Amazing_Spider-Man_theatrical_poster.jpeg", release_year: "2012",synopsis: "After Peter Parker is bitten by a genetically altered spider, he gains newfound, spider-like powers and ventures out to solve the mystery of his parent's mysterious death..")
m9 = Movie.create(movie_title: "Thor: Dark World", image: "http://img1.wikia.nocookie.net/__cb20130906231737/marveldatabase/images/8/8e/Thor_The_Dark_World_poster_006.jpg", release_year: "2014", synopsis: "When Dr Jane Foster gets cursed with a powerful object, Thor must protect it before an army and its ruthless leader try to get their hands on it to take over the remains of Earth.")
m10 = Movie.create(movie_title: "Avatar", image: "http://photos.bravenet.com/272/478/925/3/5188DCF32E.jpg", release_year: "2009", synopsis: " A Paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home..")

m1.actors << [a1, a2, a3, a4, a5, a6, a7, a8]
m2.actors << [a9, a11, a12]
m3.actors << [a8, a10, a12]
m4.actors << [a5, a10, a12,]
m5.actors << [a8, a11, a13,]
m6.actors << [a14, a16, a10]
m7.actors << [a1, a3, a5, a10]
m8.actors << [a7, a15,a8]
m9.actors << [a5, a7, a8, a10]
m10.actors << [a13, a11, a16]
